import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { defineConfig, type Connect, type Plugin } from "vite";
import { SLUGS } from "../../landing/acquisition-pages.mjs";

const root = fileURLToPath(new URL("../../landing", import.meta.url));
// The homepage, the acquisition pages generated by acquisition-pages.mjs, the storage guide, and the partner pitch.
const pages = ["index", ...SLUGS, "hardware", "partners", "partners-one-pager"];

// On Vercel, /video, /video/embed and /video/captions are rewrites to api/video.js. This answers
// them with the same function here, so the teaser video plays in dev and preview; with no Global
// Config connected it sends the player to the default video.
const video: Connect.NextHandleFunction = createRequire(import.meta.url)("../../api/video.js");
const answerVideo: Connect.NextHandleFunction = (request, response, next) => {
  const path = (request.url ?? "").split("?")[0];
  if (path === "/video" || path.startsWith("/video/")) return void video(request, response, next);
  next();
};
const videoRoutes: Plugin = {
  name: "uncloud-video-routes",
  configureServer: (server) => void server.middlewares.use(answerVideo),
  configurePreviewServer: (server) => void server.middlewares.use(answerVideo),
};

export default defineConfig({
  root,
  base: "./",
  publicDir: fileURLToPath(new URL("../../landing/public", import.meta.url)),
  plugins: [videoRoutes],
  server: { host: "127.0.0.1", port: 5174, strictPort: true },
  preview: { host: "127.0.0.1", port: 5174, strictPort: true },
  build: {
    outDir: fileURLToPath(new URL("../../artifacts/landing", import.meta.url)),
    emptyOutDir: true,
    rollupOptions: {
      input: Object.fromEntries(pages.map((name) => [name, `${root}/${name}.html`])),
    },
  },
});
