import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import { SLUGS } from "../../landing/acquisition-pages.mjs";

const root = fileURLToPath(new URL("../../landing", import.meta.url));
// The homepage plus the acquisition pages generated by acquisition-pages.mjs.
const pages = ["index", ...SLUGS];

export default defineConfig({
  root,
  base: "./",
  publicDir: fileURLToPath(new URL("../../landing/public", import.meta.url)),
  server: { host: "127.0.0.1", port: 5174, strictPort: true },
  preview: { host: "127.0.0.1", port: 5174, strictPort: true },
  build: {
    outDir: fileURLToPath(new URL("../../artifacts/landing", import.meta.url)),
    emptyOutDir: true,
    rollupOptions: {
      input: Object.fromEntries(pages.map((name) => [name, `${root}/${name}.html`])),
    },
  },
});
